version: "3.7"
services:
  ProjectZomboidDedicatedServer:
    image: danixu86/project-zomboid-dedicated-server:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
    extra_hosts:
      - "lazycat:192.168.1.99"
    network_mode: "bridge"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      # Server data
      - "/run/media/joao/MegaDrive/Games/ProjectZomboidServer/data:/home/steam/Zomboid"
      # Workshop mods folder
      - "/run/media/joao/MegaDrive/Games/ProjectZomboidServer/workshop-mods:/home/steam/pz-dedicated/steamapps/workshop"      
